### PR TITLE
Added Japanese translation.

### PR DESCRIPTION
**Pull request by teramonagi**
Hi Renkun;

I translated your gh-pages into Japanese to introduce rlist package to Japanese folks.
(Ofcourse, pipeR also too :))

I'm not sure how you redirect these pages from renkun-ken.github.io/rlist to http://renkun.me/rlist/.
But I think that you can access my translation from the following link:
- http://teramonagi.github.io/rlist/ja

### CODE REVIEW

**Comment by renkun-ken** [comment]
Nice job! Thanks! The project page is automatically generated from `README.md`. I'll try to figure out a way for the translations.

**Comment by renkun-ken** [comment]
Now http://renkun.me/rlist/ja/ works! One potential problem is when I update `README.Rmd` and knit it to produce a new `README.md`, which will be rendered as the website automatically when I choose to update the project page in *GitHub Project Settings*. I'm not sure if the manually-added folders and pages would be removed in `gh-pages` branch.

**Comment by teramonagi** [comment]
Wow! I completely missed README.Rmd!!!
How about making README_ja.Rmd? I will do it if you want :)

**Comment by teramonagi** [comment]
The file structure of "github cheat sheet" might be a good option.
- https://github.com/tiimgreen/github-cheat-sheet

**Comment by renkun-ken** [comment]
It's much easier to keep multi-language documents as multiple markdown files. Thinks it's a convenient solution.

**Comment by renkun-ken** [comment]
@teramonagi, would you like to create a `README.ja.Rmd`? I will add translation links to `README.Rmd`.

**Pull request merged**
